### ISSUE TITLE
(GUEST - SERVER) Yêu cầu khen thưởng bài báo khi gửi yêu cầu bị lỗi 

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#1005]
![image](https://user-images.githubusercontent.com/79254562/114769507-7e066100-9d94-11eb-99cc-1b6428a86502.png)

**Comment by hvu0163** [comment]
a test lại xem còn bị ko

**Comment by phucnh6997** [comment]
ok rồi nhé

**Comment by phucnh6997** [comment]
đã check lại ok rồi nhé
