### ISSUE TITLE
[Manager - Chi tiết đề nghị tham gia hội nghị chờ phê duyệt] Bảng quy trình phê duyệt thiếu tên người phê duyệt

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#1255]
![image](https://user-images.githubusercontent.com/55972353/116866317-64d72e80-ac35-11eb-9f55-a6f46b6ffca4.png)

**Comment by thang1160** [comment]
account trong db không có tên thì không hiện
