### ISSUE TITLE
Màn config drive account cho Guest/Manager

### ISSUE THREAD

**Issue by thang1160** [FPT-SAP-LAB/Science-Management-and-International-Affairs#191]
Cần 1 trường input "Thư mục gốc"
Các file được upload lên sẽ có structure folder như sau:

Thư mục gốc
|_____SonNT5
|&emsp;&emsp;|_____Khen thưởng bài báo
|&emsp;&emsp;|&emsp;&emsp;|_____Bài báo A (file đính kèm 1, file đính kèm 2)
|&emsp;&emsp;|&emsp;&emsp;|_____Bài báo B
|&emsp;&emsp;|
|&emsp;&emsp;|_____Tham dự hội nghị
|&emsp;&emsp;|&emsp;&emsp;|_____Hội nghị C (file đính kèm 1, file đính kèm 2)
|&emsp;&emsp;|&emsp;&emsp;|_____Hội nghị D
|&emsp;&emsp;|
|&emsp;&emsp;|_____Học bổng, ...vv
|
|_____AnhBN

Nếu thư mục quá phức tạp sẽ rút gọn xuống còn:

Thư mục gốc
|_____SonNT5
|&emsp;&emsp;|_____Bài báo A (file đính kèm 1, file đính kèm 2)
|&emsp;&emsp;|_____Bài báo B
|&emsp;&emsp;|_____Hội nghị C (file đính kèm 1, file đính kèm 2)
|&emsp;&emsp;|_____Hội nghị D
|&emsp;&emsp;|_____Học bổng E
|
|_____AnhBN

**Comment by N0sBa** [comment]
Chưa hiểu issue này lắm, mai  Thắng giải thích cho tôi phát

**Comment by thang1160** [comment]
Còn thiếu chỉnh sửa thư mục gốc cho IA & SM

**Comment by thang1160** [comment]
Đã bỏ 2 màn này
