### ISSUE TITLE
Các element cần padding chuẩn 1rem

### ISSUE THREAD

**Issue by thang1160** [FPT-SAP-LAB/Science-Management-and-International-Affairs#200]
![image](https://user-images.githubusercontent.com/35557579/110474161-ecab2b80-8111-11eb-86bc-b2a2dccdb679.png)

**Comment by hvu0163** [comment]
đấy là margin, kém cỏi

**Comment by hoangson99201** [comment]
![image](https://user-images.githubusercontent.com/53392660/110728157-1cac1900-824f-11eb-884d-498cb66683cb.png)

**Comment by hoangson99201** [comment]
done

**Comment by hvu0163** [comment]
đã sửa
