### ISSUE TITLE
Elements cùng thanh tìm kiếm sắp xếp chưa hợp lý tại các màn DANH SÁCH

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#201]
Xuất hiện hầu hết các màn List bên MANAGER, chưa tìm ra cách căn chỉnh hợp lý
![image](https://user-images.githubusercontent.com/44664162/110489926-60553480-8122-11eb-857e-eb017a1ad2ff.png)

**Comment by N0sBa** [comment]
![image](https://user-images.githubusercontent.com/44664162/110828850-1018d680-82ca-11eb-81d1-df14492a41e5.png)
Bên này vẫn bị Sơn ơi

**Comment by hoangson99201** [comment]
[image: image.png]
màn t chỉnh bth mà

**Comment by hoangson99201** [comment]
![image](https://user-images.githubusercontent.com/53392660/110829935-3b4ff580-82cb-11eb-8ea2-a2143abf0c8b.png)
.

**Comment by hoangson99201** [comment]
@N0sBa

**Comment by N0sBa** [comment]
![image](https://user-images.githubusercontent.com/44664162/110832449-e661ae80-82cd-11eb-96de-07a8bd6220f9.png)
@sonnhhe130366 ơi ông chỉnh lại nút Thêm k bold và độ rộng của cả thanh element phía trên bằng độ rộng của bảng nhé.

**Comment by quoctuanck99** [comment]
những phần liên quan tới filter, search để bên trái, còn các chức năng như export, thêm trường thì để bên phải nhé

**Comment by N0sBa** [comment]
> những phần liên quan tới filter, search để bên trái, còn các chức năng như export, thêm trường thì để bên phải nhé

Okay tôi nhắn @sonnhhe130366 rồi
