### ISSUE TITLE
Chưa pop-up modal đối với chức năng THÊM màn hình 'DANH SÁCH ĐỐI TÁC'

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#202]
![image](https://user-images.githubusercontent.com/44664162/110491006-6dbeee80-8123-11eb-9138-65a142f3b3cf.png)

**Comment by hoangson99201** [comment]
@N0sBa cái này thêm t tưởng là hiện ra màn giống detail chứ ko phải modal

**Comment by N0sBa** [comment]
Oke thế ông để giống phần sửa, nhảy sang hẳn trang mới luôn nhé.
Và ở phần Thêm sẽ không có trường **Lĩnh Vực** nhé
