### ISSUE TITLE
Thiết kế lại phần tìm kiếm ở list NCV bên manager

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#213]
Ở trường tìm kiếm theo ngành với cơ sở đang hơi ngắn cần kéo dài ra
Cơ sở thì viết hẳn ra không nên viết tắt CS, đang để hiển thị tìm theo năm 
![image](https://user-images.githubusercontent.com/55972353/110586013-157c0100-81a4-11eb-8e37-2ebc84583807.png)

**Comment by quoctuanck99** [comment]
**done nhé con nguyen**
