### ISSUE TITLE
Xóa cái nút xóa tác giả đi cho giống giao diện bên màn thêm đề nghị khen thưởng bài báo

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#219]
Xóa cái nút xóa tác giả đi cho giống giao diện bên màn thêm đề nghị khen thưởng bài báo

_Originally posted by @nguyenttt11 in https://github.com/FPT-SAP-LAB/Science-Management-and-International-Affairs/issues/149#issuecomment-795425916_

**Comment by thang1160** [comment]
Đã kiểm tra và thấy đồng bộ nút xóa trên server

![image](https://user-images.githubusercontent.com/35557579/115969831-39837e00-a569-11eb-8837-0c2441e9982f.png)
