### ISSUE TITLE
Thông tin tác giả ở hai màn "Đăng kí khen thưởng bằng sáng chế" và "Đăng kí khen thưởng bài báo" phần Chi phí chưa phân rõ hàng trăm, hàng triệu

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#239]
![image](https://user-images.githubusercontent.com/79254562/110770647-243de300-828c-11eb-94e1-616517addaf7.png)

**Comment by quoctuanck99** [comment]
cái này chưa có backend, khi có backend rồi thì cho xử lý ở hàm render ra các cell của datatables
