### ISSUE TITLE
Chức năng "Thêm tác giả" ở 2 màn "Đăng ký khen thưởng bài báo" và "Khen thưởng bằng sáng chế" chưa xóa hết thông tin đã điền vào khi thêm tác giả mới

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#242]
![image](https://user-images.githubusercontent.com/79254562/110774468-6b2dd780-8290-11eb-8a04-522a43719872.png)
![image](https://user-images.githubusercontent.com/79254562/110774486-6ff28b80-8290-11eb-8b67-58a2f7a6fb72.png)

**Comment by quoctuanck99** [comment]
**cái này mình để làm 2 case nhé:**
1. Sau khi user nhập người dùng mới thành công, mình sẽ ẩn popup và clear toàn bộ các trường trong đó đi
2. Khi người dùng đang nhập dở thoát ra ngoài hoặc cancel thì mình vẫn giữ các trường đang nhập dở (phòng trường hợp người dùng click nhầm ra ngoài làm tắt mất popup nhập)
3. Ngoài ra để mượt cho UX, mình có thể thêm một nút nữa là clear toàn bộ các trường trong form đang nhập cho những case người dùng muốn nhập trắng lại,
