### ISSUE TITLE
Chỉnh sửa màn đề nghị khen thưởng số trích dẫn

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#273]
Phần thông tin yêu cầu thay bằng form thêm tác giả ( ở đề nghị này chỉ có một tác giả thôi)
![image](https://user-images.githubusercontent.com/55972353/111018886-60895480-83ee-11eb-8177-aa4386443ca1.png)

**Comment by quoctuanck99** [comment]
??? không hiểu
