### ISSUE TITLE
Trạng thái màn "Danh sách đề nghị hỗ trợ hội nghị" bên MANAGER chưa đúng style css thiết kế

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#282]
![image](https://user-images.githubusercontent.com/79254562/111021709-ddbdc500-8400-11eb-90d4-30670133e116.png)

**Comment by quoctuanck99** [comment]
Cái này em check lại thì là đang thiếu filter thôi nhé anh. Còn style thì đúng rồi nhé
