### ISSUE TITLE
Nút 'Kiểm tra' tại modal Thêm/Sửa Partner trong MOU/MOA chưa bắt trường hợp trùng Partner mặc dù trước đó đã kí MOU/MOA

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#285]
Kiểm tra MOU với partner_id tương ứng -> (Danh sách các MOU của partner_id)
|___True -> Check 'mou_start_date' vừa điền <= MAX('mou_end_date') trong danh sách MOU của partner_id (mou_end_date = &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;mou_end_date trong MOU + mou_end_date nếu có trong MOUBonus)
|&emsp;&emsp;&emsp;|True -> Step1: Cảnh báo với MANAGER rằng partner_name đã kí kết với MOU trước đó và hiện thông tin chi tiết về MOU |&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;có end_date max (mou_scope, đơn vị kí kết, thời  gian có hiệu lực, thời gian kết thúc)
|&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;-> Step2: Disable nút 'Lưu'        
|&emsp;&emsp;&emsp;|False -> Check business rule khác
|___False -> Check business rule khác

**Comment by dungp99** [comment]
Đã fix rồi nhé

**Comment by N0sBa** [comment]
Đã check lại. Passed
