### ISSUE TITLE
Nút 'THÊM', 'EXPORT' cho sang phải, FILTER cho sang trái màn AcademicActivity/List

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#292]
![image](https://user-images.githubusercontent.com/44664162/111065016-0bcb0400-84ea-11eb-8281-3bd880bfb3f4.png)

**Comment by duongpl** [comment]
để thế bị conflic với các màn còn lại, giữ nguyên thế này hợp hướng nhìn hơn

**Comment by duongpl** [comment]
done
