### ISSUE TITLE
Nút 'THÊM', 'EXPORT' chưa song song với border của DATATABLE màn hình AcademicCollaboration/Shorttern_List & AcademicCollaboration/Longtern

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#293]
![image](https://user-images.githubusercontent.com/44664162/111065077-5d738e80-84ea-11eb-9413-5e21e2b24cdb.png)

**Comment by hoangson99201** [comment]
![image](https://user-images.githubusercontent.com/53392660/111070647-3f675780-8505-11eb-8994-21890fd9e8f9.png)

**Comment by N0sBa** [comment]
Đã check
