### ISSUE TITLE
Chức năng 'XEM LỊCH SỬ HOẠT ĐỘNG CỦA ĐỐI TÁC' chưa pop-up ra danh sách tương ứng

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#295]
https://user-images.githubusercontent.com/44664162/111065395-0a9ad680-84ec-11eb-988f-336b8a11417c.mp4

**Comment by hoangson99201** [comment]
@N0sBa trong mockup ko có modal này nên ko biết có những cột gì

**Comment by N0sBa** [comment]
![image](https://user-images.githubusercontent.com/44664162/111081107-3b066300-8534-11eb-84b8-50599efa87a8.png)
Đây nhé @sonnhhe130366

**Comment by N0sBa** [comment]
Đã check
