### ISSUE TITLE
Các trường ngày tháng ở các màn: Thêm đề và chỉnh sửa đề nghị hỗ trợ hội nghị chưa bắt case thời gian phải trước so với ngày hiện tại

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#318]

**Comment by thang1160** [comment]
tách sang issue #831 cho @hvu0163

**Comment by thang1160** [comment]
đã fix ở pull request #829

**Comment by thang1160** [comment]
Đã check trên server
![image](https://user-images.githubusercontent.com/35557579/114341755-b0417400-9b84-11eb-92a0-75fff699d47d.png)
![image](https://user-images.githubusercontent.com/35557579/114341765-b59ebe80-9b84-11eb-89b8-efa95214a8db.png)
