### ISSUE TITLE
Màn Đăng kí khen thưởng bằng sáng chế(Guest): Sửa vị trí button "Gửi yêu cầu" cho giống màn Đăng kí khen thưởng bài báo, Đề xuất khen thưởng trích dẫn

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#330]
![image](https://user-images.githubusercontent.com/79254562/111285729-05689380-8674-11eb-9362-d3dc6a9a60f5.png)
![image](https://user-images.githubusercontent.com/79254562/111285759-11545580-8674-11eb-97b5-63968f7ccef8.png)

**Comment by quoctuanck99** [comment]
done
