### ISSUE TITLE
Notification mất background

### ISSUE THREAD

**Issue by thang1160** [FPT-SAP-LAB/Science-Management-and-International-Affairs#35]
![image](https://user-images.githubusercontent.com/35557579/106731681-554e4680-6642-11eb-95df-505cc32ca6a6.png)

![image](https://user-images.githubusercontent.com/35557579/106731665-4f586580-6642-11eb-81c3-d6de2bfb71bd.png)

**Comment by quoctuanck99** [comment]
![image](https://user-images.githubusercontent.com/39939107/106760020-f39fd380-6665-11eb-88a3-9ddc76051bd0.png)
mất có mỗi cái hình background header thôi mà, có mất css đâu

**Comment by thang1160** [comment]
vậy sửa đi @quoctuanck99

**Comment by thang1160** [comment]
đã sửa #36
