### ISSUE TITLE
DbContext không đóng khi Exception xảy ra

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#386]
![image](https://user-images.githubusercontent.com/44664162/111740198-e73ea580-88b6-11eb-8d37-d649c34e9ddc.png)

**Comment by N0sBa** [comment]
Khi Exception xảy ra, DbContext chứa Error và nếu thực hiện các chức năng khác -> không hoạt động bình thường được do lỗi vẫn được lưu lại trước đó trong DbContext

**Comment by thang1160** [comment]
anh em chuyển qua 1 trong 2 cách này nhé, không đặt đồng thời cả 2 là readonly global nữa

![image](https://user-images.githubusercontent.com/35557579/112661690-615bc500-8e89-11eb-9091-446abfce0c97.png)
![image](https://user-images.githubusercontent.com/35557579/112661724-66207900-8e89-11eb-9b01-24d26411c31e.png)
