### ISSUE TITLE
(GUEST) Màn hình "Thêm tác giả" ở 2 màn Đăng kí khen thưởng bài báo và Đăng kí khen thưởng bằng sáng chế chưa có validate blank các trường 

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#450]
![image](https://user-images.githubusercontent.com/79254562/112302786-0af65700-8cce-11eb-9dc3-bac3843fd076.png)
![image](https://user-images.githubusercontent.com/79254562/112302808-147fbf00-8cce-11eb-993f-94c811225c33.png)

**Comment by thang1160** [comment]
Đã kiểm tra trên server
![image](https://user-images.githubusercontent.com/35557579/115969877-75b6de80-a569-11eb-95ce-1353efecc2cb.png)
