### ISSUE TITLE
(MANAGER) Màn chi tiết đề nghị hỗ trợ hội nghị sửa 2 button Xét duyệt và Yêu cầu chỉnh sửa cho giống những màn khác

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#466]
![image](https://user-images.githubusercontent.com/79254562/112460056-152d5980-8d91-11eb-994e-edbd06f3e9dc.png)
![image](https://user-images.githubusercontent.com/79254562/112460175-30986480-8d91-11eb-9ddd-30cb3df212ad.png)

**Comment by quoctuanck99** [comment]
fixed
