### ISSUE TITLE
[Guest] Màn đề nghị khen thưởng bị lỗi

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#631]
- Khi đề nghị nếu chọn đại diện nhân thưởng mà không bấm vào chọn ai nhận thưởng 
sau đó bấm gửi yêu cầu thì bị lỗi nhảy vào code mà không có alert báo lỗi

**Comment by hvu0163** [comment]
xin video thực hiện. đang ko tạo ra được lỗi để xem
