### ISSUE TITLE
[Manager] Popup thêm quyết định ở màn bài báo chờ quyết định đang bị duplicate các trường

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#633]
![image](https://user-images.githubusercontent.com/55972353/113261939-414d5b00-92fa-11eb-9a2f-646fc9d64e38.png)

**Comment by hvu0163** [comment]
2 quyết định, 1 cái cho ncv, 1 cái giảng viên

**Comment by nguyenttt11** [comment]
Phần ncv cô Nguyên chỉ xét duyệt được khen thưởng tuy nhiên ra quyết định khen thưởng thì chỉ có tháng 6 và tháng 12 mới có quyết định 
Link nghiệp vụ tham khảo: https://drive.google.com/drive/u/0/folders/1PJwcbJwoTomJFgRh9T1jGo4K5X3NfPJa

**Comment by thang1160** [comment]
Đã kiểm tra trên server

![image](https://user-images.githubusercontent.com/35557579/115970091-7e5be480-a56a-11eb-8a08-7f93b17b37a6.png)
