### ISSUE TITLE
[Manager] Màn chi tiết đề nghị hỗ trợ hội nghị bị thiếu một số chức năng

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#635]
- Thiếu phần xuất ra file word 2 đơn đề nghị 
- Chưa có function print

**Comment by thang1160** [comment]
Đã thêm xuất ra 2 đơn đề nghị ở pull request #688

**Comment by thang1160** [comment]
Đã thêm nút in ở pull request #690

**Comment by nguyenttt11** [comment]
Ở function print không được print đoạn chat

**Comment by thang1160** [comment]
Đã bỏ ở pull request #742  @nguyenttt11
