### ISSUE TITLE
(MANAGER) Thêm hồ sơ NCV mới phần Thông tin tiểu sử: 2 chức năng Thêm tiểu sử công tác và Thêm tiểu sử học tập cần thêm validate cho thời gian. Và nút Save change chưa thực hiện được

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#647]
![image](https://user-images.githubusercontent.com/79254562/113277912-71e9c080-930b-11eb-8355-b02988309353.png)
![image](https://user-images.githubusercontent.com/79254562/113278002-904fbc00-930b-11eb-89ec-2381ef722323.png)

**Comment by quoctuanck99** [comment]
đã fix, vào check lại nhé anh
