### ISSUE TITLE
[MOU/List_Deleted] Chức năng 'Tìm kiếm' chưa hoạt động

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#659]
![image](https://user-images.githubusercontent.com/44664162/113326412-cf016880-9343-11eb-9757-89d4dd7de750.png)

**Comment by dungp99** [comment]
Fix rồi nhé

**Comment by N0sBa** [comment]
Đã check lại. Passed
