### ISSUE TITLE
[Modal Add MOU] Select 'Trạng thái' chưa sử dụng select2

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#660]
![image](https://user-images.githubusercontent.com/44664162/113327352-0de3ee00-9345-11eb-9d81-98ad7f413d40.png)

**Comment by dungp99** [comment]
Fix rồi nhé

**Comment by N0sBa** [comment]
Đã check lại. Passed
