### ISSUE TITLE
[Modal Add MOU] Chưa clear `Lưu ý` sau khi Thêm thành công

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#663]
![image](https://user-images.githubusercontent.com/44664162/113333932-44256b80-934d-11eb-8105-fb66de95efc4.png)

**Comment by dungp99** [comment]
Đã fix

**Comment by N0sBa** [comment]
Đã check lại. Passed
