### ISSUE TITLE
(GUEST) Giao diện màn hình của các NCV đang không giống nhau

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#671]
![image](https://user-images.githubusercontent.com/79254562/113369130-bcf6e880-938a-11eb-98b3-2aba217752c2.png)
![image](https://user-images.githubusercontent.com/79254562/113369165-cda75e80-938a-11eb-8b5e-fa40f7c349c6.png)

**Comment by quoctuanck99** [comment]
cái này không phải bug anh ơi, anh login vào tài khoản ứng với nghiên cứu viên đó thì dĩ nhiên anh cập nhật được thông tin cho bản thân anh rồi
