### ISSUE TITLE
[MOA/Detail_MOA Add] Chưa bắt case thêm 2 đối tác giống nhau

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#675]
https://user-images.githubusercontent.com/44664162/113371091-a69f5b80-938f-11eb-83b9-e2e556b3dca2.mp4

**Comment by dungp99** [comment]
đã fix

**Comment by N0sBa** [comment]
![image](https://user-images.githubusercontent.com/44664162/113512061-21819580-958d-11eb-96ed-0e172d7853b8.png)
Tôi đã kiểm tra lại và thấy vẫn chưa bắt được

**Comment by dungp99** [comment]
Lần này được rồi nhé, sẽ check duplicate theo nhóm đối tác

**Comment by N0sBa** [comment]
Đã check lại. Passed
