### ISSUE TITLE
[MOU/Detail MOA Tab] Chưa bắt case số hiệu của trùng nhau

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#678]
![image](https://user-images.githubusercontent.com/44664162/113373011-1a436780-9394-11eb-9139-f50c51cee1d6.png)

**Comment by dungp99** [comment]
Đã fix

**Comment by N0sBa** [comment]
Đã check lại. Passed
