### ISSUE TITLE
[Manager-Chi tiết đề nghị hỗ trợ hội nghị] Sửa lại phần quy trình phê duyệt

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#694]
- Đối với người đề nghị thì Ở phần Quyền nên ghi là người đề nghị chứ không nên ghi chức vụ hoặc có thể viết thành "Người đề nghị - Chức vụ" để tránh cho kế toán bị confuse 
![image](https://user-images.githubusercontent.com/55972353/113428337-d0dd3180-9400-11eb-91d0-83e84a94354d.png)

**Comment by thang1160** [comment]
@nguyenttt11
