### ISSUE TITLE
[Guest - Đăng kí khen thưởng bài báo] Không gửi yêu cầu khen thưởng được

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#712]
-Nếu một tác giả có thông tin sẵn trong DB khi t sửa một trường thông tin nào đó khi bấm gửi yêu cầu thì bị lỗi 
- Giải pháp: t nghĩ nên disable các trường đi

**Comment by hvu0163** [comment]
xin cái ảnh, hoặc là làm lúc hết session sẽ bị thế

**Comment by nguyenttt11** [comment]
chắc là do hết session
