### ISSUE TITLE
[Manager - List danh sách bài báo đang chờ phê duyệt] 

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#713]
- Cần thêm cột trạng thái
- khi manager bấm yêu cầu chỉnh sửa thì cái bài báo cần chỉnh sửa ko  nằm trong list đang chờ phê duyệt. Cho cái cần chỉnh sửa vẫn nằm trong list đấy nhé 
![image](https://user-images.githubusercontent.com/55972353/113483443-9f7e6780-94cd-11eb-842d-3f9d93417ff8.png)
![image](https://user-images.githubusercontent.com/55972353/113483460-b2913780-94cd-11eb-99aa-547b9a9c161c.png)

**Comment by hvu0163** [comment]
đã sửa
