### ISSUE TITLE
[Manager- Màn chi tiết bài báo chờ phê duyệt] sửa lại trường tổng thưởng

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#716]
-Khi cô nguyên nhập tổng thưởng cần chuyển luôn sang dạng tiền tệ 
![image](https://user-images.githubusercontent.com/55972353/113483671-d739df00-94ce-11eb-86e1-91646ab161ce.png)
của Thắng có cái này đấy

**Comment by hvu0163** [comment]
nhập xong thì bấm ra ngoài đừng enter

**Comment by nguyenttt11** [comment]
Cái của Thắng vừa nhập nó vừa tự động tách số luôn cho Tham khảo của Thắng nhé

**Comment by hvu0163** [comment]
đã sửa
