### ISSUE TITLE
[ Manager - Màn bài báo chờ upload quyết định] Bị sai luồng

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#717]
- khi Bấm xem chi tiết một bái báo thì nút Yêu cầu chỉnh sửa ko phải là yêu cầu ncv chỉnh sửa mà là yêu cầu cô Nguyên chỉnh sửa 
như vậy thì trạng thái bài báo sẽ chuyển sang là đang duyệt 
T nghĩ là thêm nút chỉnh sửa để tránh confuse một nút hai chức năng

**Comment by hvu0163** [comment]
đã sửa
