### ISSUE TITLE
[Guest - Đăng kí khen thưởng bài báo] - Sửa lại form thông tin tác giả 

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#718]
- trường loại hợp đồng chỉ hiện ra khi chọn là giảng viên
- disable trường tiền thưởng đi

**Comment by hvu0163** [comment]
nếu chỉ giảng viên có thì tốt nhất là cho thành chọn chức danh giảng viên full-time hoặc giảng viên part-time.
Vừa dex mà sau này có thêm ai cần chọn hợp đồng thì thêm dữ liệu mà ko cần sửa code

**Comment by nguyenttt11** [comment]
Thiếu phần up cmt của tác giả

**Comment by phucnh6997** [comment]
đã check
