### ISSUE TITLE
[Manager - chi tiết đề nghị] Đơn cử công tác chưa đúng form 

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#719]
![image](https://user-images.githubusercontent.com/55972353/113485530-2df7e680-94d8-11eb-91c9-39e17e378c63.png)
ở phần kí tên ko còn người đề nghị nữa 
![image](https://user-images.githubusercontent.com/55972353/113485549-46680100-94d8-11eb-9837-6f873df62519.png)

**Comment by thang1160** [comment]
@nguyenttt11
