### ISSUE TITLE
(MANAGER) Thêm hồ sơ NCV khi chỉnh sửa thông tin không lưu thông tin mới mà vẫn hiển thị lại thông tin cũ

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#731]

**Comment by quoctuanck99** [comment]
mô tả rõ hơn bằng hình ảnh nhé anh

**Comment by phucnh6997** [comment]
![image](https://user-images.githubusercontent.com/79254562/114156693-0926c780-994d-11eb-873b-f9a34e14f2b1.png)
đây là thông tin ban đầu nhé nhưng khi chỉnh sửa rồi ấn lưu thì k lưu thông tin vừa chỉnh sửa mà vẫn là thông tin cũ

**Comment by phucnh6997** [comment]
![image](https://user-images.githubusercontent.com/79254562/114156996-5b67e880-994d-11eb-8e12-12e784ac2e09.png)

**Comment by phucnh6997** [comment]
@quoctuanck99 nó lại trở về thông tin đầu mà k lưu thông tin mới

**Comment by quoctuanck99** [comment]
đã fix, check lại và close giúp em nhé
