### ISSUE TITLE
(MANAGER) Thêm hồ sơ NCV mới nhầm label Ngày sinh thành Quốc tịch. Cần validate thêm trường Ngày sinh

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#732]
![image](https://user-images.githubusercontent.com/79254562/113505336-3b5cb180-9568-11eb-8833-4354ae05818a.png)

**Comment by phucnh6997** [comment]
Phần thông tin chung NCV cũng thế
![image](https://user-images.githubusercontent.com/79254562/113505403-d3f33180-9568-11eb-83b3-845de20e2dd3.png)

**Comment by quoctuanck99** [comment]
fixed
