### ISSUE TITLE
[AcademicActivity/List] Xảy ra lỗi khi xóa hoạt động

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#746]
![image](https://user-images.githubusercontent.com/44664162/113519349-cca64500-95b5-11eb-8c47-ff5ae333ad96.png)

**Comment by duongpl** [comment]
**đã sửa**

**Comment by N0sBa** [comment]
Đã check lại. Passed
