### ISSUE TITLE
[DetailOfAcademicActivity] Xảy ra lỗi khi chỉnh sửa nội dung

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#753]
https://user-images.githubusercontent.com/44664162/113549777-322d1c80-961c-11eb-8bf4-b624daf2640f.mp4

**Comment by duongpl** [comment]
**đã sửa**

**Comment by N0sBa** [comment]
Đã check lại. Passed
