### ISSUE TITLE
[AcademicCollaboration/Program] Danh sách chương trình bên MANAGER không giống với bên GUEST

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#755]
![image](https://user-images.githubusercontent.com/44664162/113551700-46264d80-961f-11eb-9d5a-0f4d69f203d9.png)
![image](https://user-images.githubusercontent.com/44664162/113551709-4d4d5b80-961f-11eb-81bd-ab682ac99d7f.png)

**Comment by tomuro1711** [comment]
Màn GUEST  chỉ hiển thị các chương trình có phiên bản ngôn ngữ. Ví dụ chương trình chưa có phiên bản tiếng việt sẽ không hiển thị ở màn GUEST tiếng việt.

**Comment by N0sBa** [comment]
Okay tôi đã check lại và đúng như Lâm đã cmt phía trên. Passed
