### ISSUE TITLE
[DetailOfAcademicActivity] Không bắt buộc người dùng nhập 'Ghi chú'

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#784]
![image](https://user-images.githubusercontent.com/44664162/113710763-50734500-970e-11eb-8e23-35ec175a7f4e.png)
![image](https://user-images.githubusercontent.com/44664162/113710869-70a30400-970e-11eb-9405-1af775527f74.png)

**Comment by duongpl** [comment]
done

**Comment by N0sBa** [comment]
Đã check lại. Passed
