### ISSUE TITLE
[AcademicActivity/List] Clone xảy ra lỗi trong code

### ISSUE THREAD

**Issue by N0sBa** [FPT-SAP-LAB/Science-Management-and-International-Affairs#787]
https://user-images.githubusercontent.com/44664162/113716827-2c673200-9715-11eb-9d36-a9d55d529d8f.mp4
Có thể do clone giai đoạn không có form đi kèm

**Comment by duongpl** [comment]
done

**Comment by N0sBa** [comment]
Đã check lại. Passed
