### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Hiện thị sai kết quả tìm kiếm cán bộ giảng viên

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#802]
Các trường trong tìm kiếm phải đồng thời thỏa mãn.

![Screenshot (230)](https://user-images.githubusercontent.com/47218583/113746268-5417c380-9730-11eb-950f-558bbd27ca24.png)
![Screenshot (231)](https://user-images.githubusercontent.com/47218583/113746272-5548f080-9730-11eb-9408-645583ff465f.png)

**Comment by N0sBa** [comment]
Fixed
