### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Không sửa được nội dung cán bộ

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#805]
![Screenshot (233)](https://user-images.githubusercontent.com/47218583/113748805-22542c00-9733-11eb-842a-adf8e052eabf.png)
![Screenshot (234)](https://user-images.githubusercontent.com/47218583/113748815-241def80-9733-11eb-99e8-524537d50e52.png)

**Comment by N0sBa** [comment]
Fixed

**Comment by dungp99** [comment]
Hiện tại thì file cũ không thể replace được và cũng không thể remove được file vừa mới up lên.
![image](https://user-images.githubusercontent.com/47218583/114430241-6ee2b000-9be8-11eb-9ffa-0f841078c485.png)

**Comment by N0sBa** [comment]
Hiện tại tôi đang cho chỉnh sửa theo nội dung mới nhất
Ví du:
1. Chỉnh sửa file -> Attach file muốn chỉnh sửa vào
2. Xóa file cũ -> Để trống attach file và bấm chỉnh sửa
