### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Lỗi hiển thị Range DatePicker

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#806]
1.Nội dung hiển thị trên lịch không đúng.
![Screenshot (233)](https://user-images.githubusercontent.com/47218583/113750408-f20d8d00-9734-11eb-9055-ae58ecf217ed.png)
![Screenshot (235)](https://user-images.githubusercontent.com/47218583/113750415-f33eba00-9734-11eb-86c6-08f153574105.png)
![Screenshot (236)](https://user-images.githubusercontent.com/47218583/113750420-f3d75080-9734-11eb-9424-ee764a35777d.png)

**Comment by dungp99** [comment]
"04/06/2021" : hiển thị bị ngược.

**Comment by dungp99** [comment]
![image](https://user-images.githubusercontent.com/47218583/114492933-c3ffdf80-9c43-11eb-8c65-eff37017a754.png)
Lúc click chuột vào thì nó không hiển thị được đúng ngày

**Comment by hoangson99201** [comment]
![image](https://user-images.githubusercontent.com/53392660/114501491-4a242200-9c54-11eb-8c47-5cbcdc27f533.png)
t click vào thấy bình thường mà
ông ấn chỗ nào đấy
