### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Kết quả sau khi bấm search bị sai

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#827]
1.Nhập năm đi học 2021, trả về kết quả sai
![Screenshot (244)](https://user-images.githubusercontent.com/47218583/113845881-25492e00-97c0-11eb-97cc-5555aa23ac85.png)

**Comment by N0sBa** [comment]
Tôi đã chỉnh sửa lại
