### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Lỗi xử lý trường hợp ngày đi học và ngày kết thúc

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#830]
Ngày đi học và kết thúc ở dòng 5 và dòng 6 hiện không thỏa mãn business.
![Screenshot (245)](https://user-images.githubusercontent.com/47218583/113848500-be794400-97c2-11eb-89e0-efe6b6398e98.png)

**Comment by dungp99** [comment]
Bên Ngắn hạn vẫn bị
![image](https://user-images.githubusercontent.com/47218583/114489642-ad568a00-9c3d-11eb-8f61-a7716f675472.png)

**Comment by N0sBa** [comment]
Tôi đã chỉnh sửa lại
