### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Lỗi xử lý trường hợp thêm cán bộ 

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#832]
1.Thêm cán bộ Kieu Quoc Tuan ở Chiều đi, thời gian học và kết thúc: từ 2021-2025.
2.Ở chiều đến, tiếp tục thêm cán bộ Kieu Quoc Tuan với time học và kết thúc từ 2022-2024 và vẫn thêm được dữ liệu thành công
(Expected: Không cho nhập).
![Screenshot (246)](https://user-images.githubusercontent.com/47218583/113850298-83781000-97c4-11eb-9ab2-62d5605dd504.png)

**Comment by dungp99** [comment]
1.T bây giờ vẫn nhập được Cán bộ Vu Minh Hieu ở cả 2 bên Ngắn hạn và dài hạn với khoảng thời gian không hợp lệ
![image](https://user-images.githubusercontent.com/47218583/114489152-daef0380-9c3c-11eb-9bbf-095426df6e64.png)
![image](https://user-images.githubusercontent.com/47218583/114489173-e5110200-9c3c-11eb-8e1f-8b59797e7a2c.png)

**Comment by N0sBa** [comment]
Tôi đã sửa lại rồi nhé.
Lỗi do trong phần code tôi đang bắt thêm PartnerScope lúc thêm, sửa một AcademicCollaboration
