### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Lỗi hiển thị data search cho năm đi học sau khi thêm cán bộ

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#833]
1.List data search chưa được cập nhật
![Screenshot (247)](https://user-images.githubusercontent.com/47218583/113850761-ff725800-97c4-11eb-80f4-0a23018e5bd4.png)

**Comment by dungp99** [comment]
Sau khi thêm mới thì hiện vẫn chưa list được hết 
![image](https://user-images.githubusercontent.com/47218583/114488096-f1945b00-9c3a-11eb-93c1-0576c4041db9.png)

**Comment by N0sBa** [comment]
Tôi đã sửa lại rồi nhé
