### ISSUE TITLE
[Guest] Lỗi phần comment của các màn đề nghị 

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#865]
![image](https://user-images.githubusercontent.com/55972353/114153370-720c4080-9949-11eb-99d9-34d1aa577899.png)
![image](https://user-images.githubusercontent.com/55972353/114153399-789ab800-9949-11eb-9f89-b4e26d2ec204.png)
![image](https://user-images.githubusercontent.com/55972353/114153439-83ede380-9949-11eb-82a2-b63425f30637.png)

**Comment by thang1160** [comment]
Đã fix @nguyenttt11

**Comment by nguyenttt11** [comment]
đã check
