### ISSUE TITLE
(GUEST) Đăng kí khen thưởng bằng sáng chế nút chỉnh sửa thông tin tác giả chưa thực hiện được

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#875]

**Comment by hvu0163** [comment]
Chưa thực hiện được trường nào, cho e xin cái ảnh

**Comment by phucnh6997** [comment]
a nhầm

**Comment by phucnh6997** [comment]
a nhầm là Màn đăng kí khen thưởng bằng sáng chế nha
![image](https://user-images.githubusercontent.com/79254562/114269745-cb9c6a00-9a32-11eb-90e8-ab5230a97c01.png)

**Comment by phucnh6997** [comment]
đã check
