### ISSUE TITLE
Sửa lại các preloader cho giống nhau

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#884]
![image](https://user-images.githubusercontent.com/79254562/114214420-7ad33580-998e-11eb-866c-571b61e0e710.png)
![image](https://user-images.githubusercontent.com/79254562/114214430-7e66bc80-998e-11eb-9ff5-45110693a6af.png)

**Comment by thang1160** [comment]
Đã fix với màn thêm và sửa đề nghị hội nghị @phucnh6997
