### ISSUE TITLE
(MANAGER) Danh sách đề nghị đang xử lý sửa lại giao diện cho giống những màn khác

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#891]
![image](https://user-images.githubusercontent.com/79254562/114262800-34242080-9a0c-11eb-819a-0ee8639e8dec.png)
![image](https://user-images.githubusercontent.com/79254562/114262818-456d2d00-9a0c-11eb-90e2-39a01757d4e3.png)

**Comment by quoctuanck99** [comment]
fixed
