### ISSUE TITLE
[Server-Guest-Đề nghị đăng ký khen thưởng bài báo] bị lỗi 

### ISSUE THREAD

**Issue by nguyenttt11** [FPT-SAP-LAB/Science-Management-and-International-Affairs#892]
![image](https://user-images.githubusercontent.com/55972353/114266683-bec34a80-9a21-11eb-8900-ec9d721307cd.png)
![image](https://user-images.githubusercontent.com/55972353/114266688-ca167600-9a21-11eb-9b26-734ef21d2531.png)

![image](https://user-images.githubusercontent.com/55972353/114266678-b3701f00-9a21-11eb-8a17-9ef08d001b73.png)

**Comment by hvu0163** [comment]
đã sửa
