### ISSUE TITLE
(GUEST - Server) Chỉnh sửa thông tin NCV thêm tiểu sử học tập đang bị lỗi 

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#910]
![image](https://user-images.githubusercontent.com/79254562/114304170-facade00-9afb-11eb-9c65-2b9a60428dc9.png)

**Comment by thang1160** [comment]
Đã kiểm tra trên server
![image](https://user-images.githubusercontent.com/35557579/115970221-3ee1c800-a56b-11eb-9260-ccc1206b3d27.png)
