### ISSUE TITLE
(MANAGER - GUEST) Chỉnh sửa thông tin NCV lỗi label

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#911]
![image](https://user-images.githubusercontent.com/79254562/114304379-079c0180-9afd-11eb-9891-3b3f7bc99622.png)

**Comment by quoctuanck99** [comment]
đã fix, check lại và close nhé anh

**Comment by phucnh6997** [comment]
đã check
