### ISSUE TITLE
(GUEST) Đề nghị hỗ trợ hội nghị sửa lại nút Chi tiết

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#913]
![image](https://user-images.githubusercontent.com/79254562/114309253-cb729c00-9b10-11eb-87ef-413699e5cd65.png)

**Comment by quoctuanck99** [comment]
để như vậy được rồi nhé anh, vì có nhiều loại nút khác nhau nên hiếu đang để code từng nút có nội dung và màu khác nhau, nhìn cũng ok không vấn đề
