### ISSUE TITLE
(GUEST) Đăng ký khen thưởng trích dẫn khi tạo yêu cầu với tên tác giả là tiếng việt thì khi tạo yêu cầu xong màn hình view bị lỗi font chữ

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#914]
![image](https://user-images.githubusercontent.com/79254562/114309698-44bebe80-9b12-11eb-92f9-46ecb9439625.png)
![image](https://user-images.githubusercontent.com/79254562/114309719-5f913300-9b12-11eb-9b21-d13142bff128.png)

**Comment by hvu0163** [comment]
đã sửa
