### ISSUE TITLE
Chuyển về thêm tuần tự ở back-end khen thưởng bài báo

### ISSUE THREAD

**Issue by thang1160** [FPT-SAP-LAB/Science-Management-and-International-Affairs#929]
![image](https://user-images.githubusercontent.com/35557579/114342443-0d89f500-9b86-11eb-9163-e25218bb2717.png)

**Comment by hvu0163** [comment]
đã sửa

**Comment by thang1160** [comment]
hiện đang lồng 4 ajax vào nhau, sửa về 1 đi
![image](https://user-images.githubusercontent.com/35557579/114661246-e61b5f80-9d20-11eb-94c0-a187cf48687a.png)
![image](https://user-images.githubusercontent.com/35557579/114661262-eb78aa00-9d20-11eb-833e-b56d5046c68d.png)

**Comment by thang1160** [comment]
@hvu0163

**Comment by hvu0163** [comment]
bên paper sửa rồi
