### ISSUE TITLE
[AcademicCollaboration/Longterm_List] Báo lỗi khi người dùng nhấn vào dòng chưa có bản mềm nào.

### ISSUE THREAD

**Issue by dungp99** [FPT-SAP-LAB/Science-Management-and-International-Affairs#941]
![Screenshot (249)](https://user-images.githubusercontent.com/47218583/114487710-42f01a80-9c3a-11eb-912e-f2cfa953ecf7.png)
![Screenshot (250)](https://user-images.githubusercontent.com/47218583/114487712-44b9de00-9c3a-11eb-93c2-993ecda4379d.png)

**Comment by N0sBa** [comment]
Tôi đã sửa lại
