### ISSUE TITLE
(GUEST) Sản phẩm khoa học đang chờ phê duyệt chưa define màu các trạng thái

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#960]
![image](https://user-images.githubusercontent.com/79254562/114570502-1242cc00-9ca0-11eb-99ad-ae27e1a0b846.png)

**Comment by quoctuanck99** [comment]
cái này có thể tạm thời close nhé a, bug này để sau
