### ISSUE TITLE
(GUEST) Chỉnh sửa thông tin trích dẫn: Sau khi bị yêu cầu chỉnh sửa lại, thêm các trường thông tin trích dẫn mới thì không lưu đc

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#993]
![image](https://user-images.githubusercontent.com/79254562/114691730-2ccd8180-9d42-11eb-9525-f834791c5892.png)
![image](https://user-images.githubusercontent.com/79254562/114691767-3525bc80-9d42-11eb-8ef5-b80083b0d4b7.png)

**Comment by hvu0163** [comment]
đã sửa

**Comment by phucnh6997** [comment]
đã check ok
