### ISSUE TITLE
(MANAGER) Chỉnh sửa thông tin NCV thiếu chức năng thêm Giải thưởng

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#994]
![image](https://user-images.githubusercontent.com/79254562/114692312-b7ae7c00-9d42-11eb-8ac9-f47cf6a8a88b.png)

**Comment by quoctuanck99** [comment]
đã fix, check and close nhé anh

**Comment by phucnh6997** [comment]
đã check ok nhé
