### ISSUE TITLE
(GUEST) Chỉnh sửa thông tin NCV các trường thời gian Tiểu sử công tác, Tiểu sử học tập, GIải thưởng thêm validate không qua so với ngày hiện tại

### ISSUE THREAD

**Issue by phucnh6997** [FPT-SAP-LAB/Science-Management-and-International-Affairs#995]
![image](https://user-images.githubusercontent.com/79254562/114692776-1ffd5d80-9d43-11eb-9f18-ca166b94e2bd.png)
![image](https://user-images.githubusercontent.com/79254562/114692788-24c21180-9d43-11eb-9dbe-6345c7e4c448.png)
![image](https://user-images.githubusercontent.com/79254562/114692847-34d9f100-9d43-11eb-8a2c-a64f20aaaa64.png)

**Comment by phucnh6997** [comment]
Bên manager cũng thế nhé @quoctuanck99

**Comment by quoctuanck99** [comment]
fixed. check and close nhé a
